version: '3'

services:
  db:
    image: postgres
  web:
    build: .
    command: python3 api/manage.py runserver 0.0.0.0:8000
    # command: gunicorn --env DJANGO_SETTINGS_MODULE=api.api.settings api.api.wsgi #—-log-file
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    depends_on:
      - db
